### ISSUE TITLE
Feature request: File encryption

### ISSUE THREAD

**Issue by DRTAC7** [DRTAC7/aegis#4]
- Add a `aegis -f file` option
- This function will take any file, read the data from the file, and run it through `aegis's` encryption algorithm. 
- It will then output the file as an `.agsx` file.
- running `aegis -d file` will decrypt the file back to its original state, including filetype.
- `aegis` will only output the decryption key to a separate file, with the same name as the encrypted file, with file extension `.agsk`
- this will allow users to, among other things, upload encrypted files to `pub`, and provide the decryption key to specific users

- requested by gunpointg

**Comment by 25zcj01** [comment]
This is proving to be a lot harder than I initially envisioned.  It seems that `aegis` doesn't like files that are converted to `.agsx` format, and when it tries to decrypt 'em it seems to break the script.  No clue why, will experiment more.

**Comment by DRTAC7** [comment]
It might not be encoding carriage returns correctly. 

Can you post the terminal output that results from your experiments?

**Comment by 25zcj01** [comment]
That was my guess too, until I tried a file without any newlines, still didn't work.  

```
@_aegis -df dtmftxt                                                                    [run _aegis.bas -df dtmftxt]

3܉5OG]|^|m|EϿx|ge: 
.إz>yקqy魊,ږ"+Z*'!N

Terminating AEGIS
```

^ That was trying to decode the `dtmf.txt` file that's on nexum.

**Comment by 25zcj01** [comment]
Just returned a `~` when trying to decrypt a plain file that just says `foo bar baz`, no newlines or other funny business.

**Comment by DRTAC7** [comment]
Whut?
Try encrypting a `.ags` file and decrypting it.
Don't try to decrypt of file that does not contain ags code,  of course that wont work

**Comment by 25zcj01** [comment]
Sorry, worded that weirdly.  Meant to say that I tried decrypting a file _that I encrypted with aegis_ that just said `foo bar baz`, without newlines or anything.

**Comment by 25zcj01** [comment]
Did a tiny bit of testing, it seems that regularly encoding a message with CRs in it without any issues, so it kinda seems like it's an issue with the 'getting characters from the file' bit.

**Comment by DRTAC7** [comment]
Can you add a file to the repo called `zcj_aegis.bas` or something like that, so I can take a look at what you have? :)

**Comment by 25zcj01** [comment]
[zcj_aegis.txt](https://github.com/DRTAC7/aegis/files/8056787/zcj_aegis.txt)

GitHub doesn't like the `.bas` extension, so I went with `.txt` instead.  Again, pretty gnarly.

**Comment by DRTAC7** [comment]
@25zcj01 Nevermind. I will find a way to do this differently in the future.
It is better that I do this myself since I understand the encryption algorithm.

**Comment by 25zcj01** [comment]
Alrighty.  I can certainly imagine that being familiar with the algorithm would help.
